gemini-hlsw/lucuma-itc

.github/workflows/ci.yml
modules/itc/src/main/scala/lucuma/itc/ItcInstrumentDetails.scala
modules/service/src/main/resources/graphql/itc.graphql
modules/service/src/main/scala/lucuma/itc/service/ItcMappings.scala
modules/service/src/main/scala/lucuma/itc/service/ItcService.scala
modules/service/src/main/scala/lucuma/itc/service/Main.scala
modules/service/src/test/scala/lucuma/itc/service/GraphQLSuite.scala

Connect to the upstream itc backend

---

.gitignore
build.sbt
modules/service/src/main/scala/lucuma/itc/service/Config.scala
modules/service/src/main/scala/lucuma/itc/service/Main.scala

Read the itc url from the environment

Read the itc url from the configuration

---

.mergify.yml
README.md
modules/itc/src/main/scala/lucuma/itc/Itc.scala
modules/itc/src/main/scala/lucuma/itc/ItcImpl.scala
modules/itc/src/main/scala/lucuma/itc/ItcInstrumentDetails.scala
modules/itc/src/main/scala/lucuma/itc/ItcObservingConditions.scala
modules/itc/src/main/scala/lucuma/itc/search/Search.scala
modules/itc/src/main/scala/lucuma/itc/search/syntax/ConditionsOps.scala
modules/itc/src/main/scala/lucuma/itc/search/syntax/GmosNorthDisperser.scala
modules/itc/src/main/scala/lucuma/itc/search/syntax/GmosNorthFilter.scala
modules/itc/src/main/scala/lucuma/itc/search/syntax/GmosNorthFpu.scala
modules/itc/src/main/scala/lucuma/itc/search/syntax/package.scala
modules/service/src/main/scala/lucuma/itc/service/ItcMappings.scala

Fixes serialization of params to ocs2 values

---

README.md
modules/service/src/main/scala/lucuma/itc/service/Main.scala
modules/service/src/main/scala/lucuma/itc/service/config/Config.scala
modules/service/src/main/scala/lucuma/itc/service/config/Environment.scala

Support CORS

---

modules/service/src/main/resources/graphql/itc.graphql
modules/service/src/main/scala/lucuma/itc/service/ItcMappings.scala
modules/service/src/test/scala/lucuma/itc/service/GraphQLBasicCaseSuite.scala
modules/service/src/test/scala/lucuma/itc/service/GraphQLSpectroscopySuite.scala
modules/service/src/test/scala/lucuma/itc/service/GraphQLSuite.scala

Improves handling of bigdecimal as a String

Improvements to handling values in variables

---

modules/itc/src/main/scala/lucuma/itc/ItcImpl.scala
modules/service/src/main/scala/lucuma/itc/service/ItcMappings.scala
modules/service/src/main/scala/lucuma/itc/service/ItcService.scala
modules/service/src/main/scala/lucuma/itc/service/Main.scala

Improve tracing and caching

---

modules/itc/src/main/scala/lucuma/itc/Itc.scala
modules/itc/src/main/scala/lucuma/itc/ItcImpl.scala
modules/service/src/main/resources/graphql/itc.graphql
modules/service/src/main/scala/lucuma/itc/service/ItcMappings.scala
modules/service/src/test/scala/lucuma/itc/service/GraphQLSuite.scala

Signal to noise should be BigDecimal

---

.scalafmt.conf
project/plugins.sbt

Some updates

---

build.sbt

Switch to the new itc server

---

build.sbt

Restore logging

---

modules/benchmarks/src/test/scala/lucuma/itc/LegacyITCSimulation.scala
modules/itc/src/main/scala/lucuma/itc/ItcImpl.scala
modules/service/src/main/scala/lucuma/itc/service/ItcMappings.scala
modules/service/src/test/scala/lucuma/itc/service/GraphQLSpectroscopySuite.scala

Conditions coming from explore weren't correctly parsed in all cases. This fixes it and adds a test to ensure all condition values can be parsed

Conditions

---

modules/service/src/main/scala/lucuma/itc/service/ItcMappings.scala
modules/service/src/main/scala/lucuma/itc/service/syntax/ItcSyntax.scala
modules/service/src/test/scala/lucuma/itc/service/GraphQLSpectroscopySuite.scala

Airmass has be restricted to a few buckets for the legacy ITC. There are also some improvements to error handling

Airmass limit

---

modules/service/src/main/resources/graphql/itc.graphql
project/build.properties

Small code comment

---

modules/benchmarks/src/test/scala/lucuma/itc/LegacyITCSimulation.scala
modules/itc/src/main/scala/lucuma/itc/ItcInstrumentDetails.scala
modules/itc/src/main/scala/lucuma/itc/search/ObservingMode.scala
modules/itc/src/main/scala/lucuma/itc/search/syntax/GmosSouthDisperser.scala
modules/itc/src/main/scala/lucuma/itc/search/syntax/GmosSouthFilter.scala
modules/itc/src/main/scala/lucuma/itc/search/syntax/GmosSouthFpu.scala
modules/itc/src/main/scala/lucuma/itc/search/syntax/package.scala
modules/service/src/main/resources/graphql/itc.graphql
modules/service/src/main/scala/lucuma/itc/service/ItcMappings.scala
modules/service/src/test/scala/lucuma/itc/service/GraphQLSpectroscopySuite.scala

Support Gmos South

---

modules/benchmarks/src/test/scala/lucuma/itc/BasicITCChecks.scala
modules/benchmarks/src/test/scala/lucuma/itc/LegacyITCSimulation.scala
modules/itc/src/main/scala/lucuma/itc/Itc.scala
modules/itc/src/main/scala/lucuma/itc/ItcImpl.scala
modules/itc/src/main/scala/lucuma/itc/ItcResult.scala
modules/service/src/main/scala/lucuma/itc/service/ItcMappings.scala

This is an updated version of the algorithm to select the exp time and exposures. It also adds a gatling test to verify the results

Replace algorithm

---

build.sbt
modules/benchmarks/src/test/scala/lucuma/itc/BasicITCChecks.scala
modules/itc/src/main/scala/lucuma/itc/ItcImpl.scala

Algorithm updates

---

modules/benchmarks/src/test/scala/lucuma/itc/BasicITCChecks.scala
modules/itc/src/main/scala/lucuma/itc/ItcImpl.scala

Fixes a reversed param and add a test case

---

modules/benchmarks/src/test/scala/lucuma/itc/BasicITCChecks.scala
modules/itc/src/main/scala/lucuma/itc/search/syntax/ConditionsOps.scala

Fix cloud extinction mapping

---

modules/itc/src/main/scala/lucuma/itc/search/syntax/ConditionsOps.scala
modules/service/src/main/scala/lucuma/itc/service/ItcMappings.scala

Replace custom item mapping

---

modules/service/src/main/scala/lucuma/itc/service/ItcMappings.scala
modules/service/src/test/scala/lucuma/itc/service/GraphQLSpectroscopySuite.scala

Signed-off-by: Carlos Quiroz <3615303+cquiroz@users.noreply.github.com>

Support uniform source profiles

---

modules/service/src/main/resources/assets/playground.html
modules/service/src/main/resources/graphql/itc.graphql

Signed-off-by: Carlos Quiroz <3615303+cquiroz@users.noreply.github.com>

Cleanup old schema

---

modules/service/src/main/resources/graphql/itc.graphql
modules/service/src/main/scala/lucuma/itc/service/ItcMappings.scala
modules/service/src/test/scala/lucuma/itc/service/GraphQLSpectroscopySuite.scala

Support Gaussian sources

---

modules/itc/src/main/scala/lucuma/itc/ItcCalculationError.scala
modules/itc/src/main/scala/lucuma/itc/ItcImpl.scala
modules/service/src/main/scala/lucuma/itc/service/ItcMappings.scala
modules/service/src/test/scala/lucuma/itc/service/GraphQLSpectroscopySuite.scala

Fix magnitude conversion and better handling of calculation errors

---

.gitignore
flake.nix
modules/benchmarks/src/test/scala/lucuma/itc/BasicITCChecks.scala
modules/benchmarks/src/test/scala/lucuma/itc/LegacyITCSimulation.scala
modules/itc/src/main/scala/lucuma/itc/ItcInstrumentDetails.scala
modules/itc/src/main/scala/lucuma/itc/search/ObservingMode.scala
modules/itc/src/main/scala/lucuma/itc/search/Search.scala
modules/service/src/main/resources/graphql/ObservationDB.graphql
modules/service/src/main/resources/graphql/itc.graphql
modules/service/src/main/scala/lucuma/itc/service/ItcMappings.scala
modules/service/src/test/scala/lucuma/itc/service/GraphQLSpectroscopySuite.scala

Adopt  changes from the latest odb schema in production

Sync schema with odb

---

modules/service/src/main/resources/graphql/ObservationDB.graphql
modules/service/src/main/resources/graphql/itc.graphql
modules/service/src/main/scala/lucuma/itc/service/ItcMappings.scala
modules/service/src/test/scala/lucuma/itc/service/GraphQLSpectroscopySuite.scala

Sync the schema with the one on the master odb. e.g. rename disperser to grating

Odb master

---

modules/itc/src/main/scala/lucuma/itc/ItcChart.scala
modules/service/src/main/scala/lucuma/itc/service/ItcService.scala
modules/service/src/main/scala/lucuma/itc/service/Main.scala

Enable compression and reduce cache time

Enable gzip

---

modules/service/src/main/resources/graphql/itc.graphql
modules/service/src/main/scala/lucuma/itc/service/ItcMappings.scala
modules/service/src/test/scala/lucuma/itc/service/GraphQLSpectroscopyGraphSuite.scala

I had marked the endpoint as "beta" but we are now putting it in production

Rename the graph endpoint

---

modules/itc/src/main/scala/lucuma/itc/Itc.scala
modules/itc/src/main/scala/lucuma/itc/ItcImpl.scala
modules/itc/src/main/scala/lucuma/itc/search/Search.scala
modules/service/src/main/resources/graphql/itc.graphql
modules/service/src/main/scala/lucuma/itc/service/ItcMappings.scala
modules/service/src/main/scala/lucuma/itc/service/ItcPartials.scala
modules/service/src/test/scala/lucuma/itc/service/GraphQLSNSuite.scala
modules/service/src/test/scala/lucuma/itc/service/GraphQLSpectroscopyGraphSuite.scala
modules/service/src/test/scala/lucuma/itc/service/GraphQLSuite.scala

Add a new experimental end point to return S/N for a given mode and parameters.
It also supports a `signalToNoiseAt` wavelength parameter to specify the wavelength used for the calculation

Signal to noise

---

build.sbt
modules/service/src/main/scala/lucuma/itc/GraphResult.scala
modules/service/src/main/scala/lucuma/itc/ItcImpl.scala
modules/service/src/main/scala/lucuma/itc/legacy/LocalItc.scala
modules/service/src/main/scala/lucuma/itc/package.scala
modules/service/src/main/scala/lucuma/itc/service/ItcMappings.scala
modules/service/src/main/scala/lucuma/itc/service/Main.scala

Some of the legacy errors are multi line which can produce some problems when trying to display them. This PR improves what is sent to the client splitting the files

Better error encoding

---

build.sbt
modules/service/src/main/scala/lucuma/itc/ItcImpl.scala
modules/service/src/main/scala/lucuma/itc/legacy/IOLocalItc.scala
modules/service/src/main/scala/lucuma/itc/legacy/LocalItc.scala
modules/service/src/main/scala/lucuma/itc/service/Main.scala

This is an internal refactoring to remove some duplicated code and to ensure local itc calls respect IO fairness

General cleanup and improve blocking calls

---

modules/service/src/main/scala/lucuma/itc/service/ItcMappings.scala
modules/service/src/main/scala/problem.scala

Internalize fixed grackle code

Include code to fix extensions field

---

modules/service/src/main/scala/lucuma/itc/service/ItcMappings.scala

An update to Raul's PR to work around Grackle's new input value limit.

Update input depth limit

---

modules/service/src/main/scala/lucuma/itc/GraphResult.scala

In same edge cases, ITC results included NaN values, we'll just  filter them out

Filter chart result removing NaN results

---

modules/service/src/main/scala/lucuma/itc/legacy/codecs.scala

It was requested that whenever ITC computes a result with zero S/N, we should inform of that.

Attempt legacy decoding of S/N first

---

.github/workflows/ci.yml
build.sbt
modules/benchmarks/src/test/scala/lucuma/itc/BasicITCChecks.scala
modules/service/src/main/resources/graphql/itc.graphql
modules/service/src/main/scala/lucuma/itc/ItcImpl.scala
modules/service/src/main/scala/lucuma/itc/search/ObservingMode.scala
modules/tests/src/test/scala/lucuma/itc/service/GraphQLIntTimeErrorsSuite.scala
modules/tests/src/test/scala/lucuma/itc/service/GraphQLSpectroscopyTimeEmissionLineSuite.scala
modules/tests/src/test/scala/lucuma/itc/service/GraphQLSpectroscopyTimeSuite.scala

We have a resolution field which is unused and complicates life for F2
This PR removes it and I'm also experimenting with an action that checks for schema changes

No resolution

---

build.sbt
modules/service/src/main/resources/graphql/itc.graphql
modules/service/src/main/scala/lucuma/itc/service/redis.scala

Bring tthe latest changes, in particular the updated list of SEDs

Update odb schema

---

modules/client/shared/src/main/scala/lucuma/itc/client/json/UnnormalizedSedJson.scala

Client logic for custom SEDs was missing.

Fix custom seds in client

---

modules/service/src/main/scala/lucuma/itc/service/Main.scala
modules/service/src/main/scala/lucuma/itc/service/requests/graph.scala
modules/service/src/main/scala/lucuma/itc/service/requests/imagingTime.scala
modules/service/src/main/scala/lucuma/itc/service/requests/package.scala
modules/service/src/main/scala/lucuma/itc/service/requests/spectroscopyTime.scala

Related to
https://app.shortcut.com/lucuma/story/5098/error-calculating-itc-invalid-tagged-type

Better errror message if there is no SED provided

---

.github/workflows/ci.yml
build.sbt

I sucks to wait for the build and tests only to find you needed the `expected-breaking-change` label.

Validate schema before running build

---

project/build.properties
project/plugins.sbt

Reverts gemini-hlsw/lucuma-itc#997

Revert "basic test"
